### ISSUE TITLE
Deep links with the city name

### ISSUE THREAD

**Issue by pietrodn** [Guglio95/posso-uscire#1]
Hello, first of all thank you for the work, you application is exceptional! 🎉 

It would be amazing if one could bookmark the direct ("deep") link to `possouscire.casa` with the city name already set (e.g., `https://possouscire.casa/milano`).
This way, the information about one's own city would be immediately available in 1 click.

Thank you!

**Comment by aguglie** [comment]
Hello Pietro,

That's a super idea!

I found tons of react-routing-libraries but they all seemed an overkill for our use case.... my brief implementation should do the trick 😄 

`https://possouscire.casa/#Milano`

Thank you for the tip,
Andrea

**Comment by pietrodn** [comment]
Amazing, thanks!
