### ISSUE TITLE
Add links to the different kinds of autodichiarazione

### ISSUE THREAD

**Issue by mahlzahn** [Guglio95/posso-uscire#10]
Thanks for this nice website!

Especially for non-Italian speaking (like me) it is hard to find the right self declarations for the cases where this is needed (travel between regions, going out after 22:00). It would be nice to directly have the link to the corresponding pdf.

**Comment by aguglie** [comment]
Hello 😄 
I'm quite sure there's only a unique self-declaration for all the above cases, I'll gather more info and put a link to it. 
Ty

**Comment by aguglie** [comment]
Hello,
I really forgot about this :) 
Now it's no more an issue.
Ty
