### ISSUE TITLE
Zona arancio scuro/rafforzata

### ISSUE THREAD

**Issue by Danielerebel** [Guglio95/posso-uscire#12]
Da oggi, invece, in tutta la Lombardia sono vietati gli spostamenti verso le abitazioni private ubicate nel territorio della regione, fatti salvi gli spostamenti motivati da comprovate e gravi situazioni di necessità. In parole semplici, non si possono più andare a trovare parenti e amici, nemmeno all’interno del proprio Comune. Si ricorda, inoltre, che gli spostamenti verso le altre regioni non sono consentiti fino al prossimo 27 marzo.

**Comment by aguglie** [comment]
Ciao! Dovrebbe essere risolto 😄 
Grazie
