### ISSUE TITLE
Pubblicazione licenza

### ISSUE THREAD

**Issue by lrsb** [Guglio95/posso-uscire#4]
Caro Guglio95, ti chiedo se potresti pubblicare una licenza d'uso sul repository.

Sarebbe interessante usare il tuo progetto come base di dati per un'applicazione (in react magari) per aprire la possibilità ad altri scenari d'uso come notifiche day by day, per aggiornamenti sulle misure, ecc.

Ti ho scritto una mail così hai il mio contatto nel caso fossi interessato.

**Comment by aguglie** [comment]
Ciao! 
Ottima idea, ho aggiunto la licenza GPLv3 per mantenere il sorgente libero 👍
