### ISSUE TITLE
seconde case

### ISSUE THREAD

**Issue by hybridassistant** [Guglio95/posso-uscire#8]
l'indicazione sulle seconde case non sembra essere corretta
lo spostamento è sempre consentito anche fuori regione secondo le ultime norme
https://www.ilmessaggero.it/politica/seconde_case_zona_rossa_zona_arancione_zona_gialla_cosa_si_puo_fare_ultima_ora_19_gennaio_2021-5710637.html

**Comment by Pasquic** [comment]
Stiamo tenendo monitorata la situazione poiché quella della possibilità di raggiungerle è un'interpretazione che ancora non ha avuto ne conferme ne smentite da parte del governo (in particolare, i ministri Boccia e Speranza si son detti all'oscuro di questa possibilità). Il dubbio nasce dalla definizione di "abitazione" che secondo le vecchie faq del governo non riconosce le seconde case come tali. Aspettiamo che escano quelle aggiornate per poter correggere eventuali interpretazioni.

Riporto in calce la definizione di Abitazione data dal governo fino al 15 gennaio:
"Abitazione. Il concetto di abitazione non ha una precisa definizione tecnico-giuridica. Ai fini dell’applicazione del dpcm, dunque, l’abitazione va individuata come il luogo dove si abita di fatto, con una certa continuità e stabilità (quindi per periodi continuativi, anche se limitati, durante l’anno) o con abituale periodicità e frequenza (per esempio in alcuni giorni della settimana per motivi di lavoro, di studio o per altre esigenze), tuttavia sempre con esclusione delle seconde case utilizzate per le vacanze"

**Comment by aguglie** [comment]
Se ci sono novità vediamo come procedere.

**Comment by aguglie** [comment]
@hybridassistant riapri pure se hai novità
